title: Aditya Bhat
email: aditya.s.bhat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Scientist, Software Developer, Reformed Banker
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asbhat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adityasbhat
github_username:  asbhat
google_analytics: UA-100975740-1

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
